### ISSUE TITLE
DirectQuery in PowerBI: We couldn't fold the expression of the data source

### ISSUE THREAD

**Issue by datawire1337** [mariadb-corporation/mariadb-powerbi#12] opened 2021-04-10 19:32 UTC
Hello,

Whenever I try to add a database field to a table (even an empty one) in PowerBI it gives me this message:
OLE DB or ODBC error: [Expression.Error] We couldn't fold the expression to the data source. Please try a simpler expression..

Any aggregates do not work either, they give me the same error.

I simply can't seem to get around this.

Thanks in advance!

**Comment by ilyagithub1** [comment] 2021-08-27 18:55
@datawire1337 
It really depends on the specific query that Power BI is creating behind the scenes for your tables and fields.

It seems that the data in question is numeric, so it is possible that the root cause is the same as in issue #4, for which a fix has been provided in the latest version of Maria DB Connector for Power BI that ships with Power BI Desktop v2.96.901.0 (Date Published: 8/24/2021) and later.

Thus, a simple way is to upgrade to the latest Power BI Desktop.

In case you would like to have more insight, you might want to examine the analysis of the fix provided in https://github.com/mariadb-corporation/mariadb-powerbi/issues/4#issuecomment-762436498. The root cause there was that Power BI Mashup Engine generated a SQL statement not supported by MariaDB Server. In many cases, a folding error could mean the same thing - an unsupported SQL statement.

If you need further assistance, please provide steps to reproduce your issue. Using Power BI Diagnostics Options might be very helpful. See detailed steps with screenshots on how to enable tracing in Power BI Desktop in https://github.com/mariadb-corporation/mariadb-powerbi/issues/10#issuecomment-850541292.

**Closed as completed by ilyagithub1** 2021-08-27 18:55 UTC
